import type { Metadata } from 'next';

import './globals.css';
import { sourceCodePro } from '@/lib/fonts';
import { cn } from '@/lib/utils';
import Providers from '@/providers';

import Footer from './(home)/_components/footer';
import Header from './(home)/_components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'flex min-h-screen flex-col antialiased',
          sourceCodePro.className
        )}
      >
        <Providers>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
